import Head from 'next/head';

const MetaData = () => {
  return (
    <Head>
      <title>Reusable Components</title>
      <meta property="description" content="Generated by create next app" />
      <meta property="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/icc.ico" />
    </Head>
  );
};

export default MetaData;