import Head from 'next/head';

const MetaData = () => {
  return (
    <Head>
      <title>Reusable Components</title>
      <meta property="description" content="Generated by create next app" />
      <meta property="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/images/icc.ico" />
      <link rel="shortcut icon" href="/images/favicon.ico" />
      <link rel="apple-touch-icon" sizes="180x180" href="/images/icc.ico" />
      <link rel="icon" type="image/png" sizes="32x32" href="/images/icc.ico"/>
      <link rel="icon" type="image/png" sizes="16x16" href="/icc.ico"/>
    </Head>
  );
};

export default MetaData;